### ISSUE TITLE
question - Is there any way to run different networks and assign them for different users? 

### ISSUE THREAD

**Issue by reinethernal** [cad/ovpm#107]
Hi! Can i run multiple networks for multiple users and assign users to than networks? 
i.e net1 - 10.9.8.0/22 for users - net1user1, net1user2 receiving 10.9.8.2/22 109.8.3/22 , 
net2 - 10.9.7.0/22 for users - net2user1, net2user2 receiving 10.9.7.2/22 109.7.3/22 ,
And ofcource i don't need users from net1 be able to icmp, etc users from net2 vice versa.

**Comment by cad** [comment]
@reinethernal unfortunately "network" in OVPM represents an external network not a logical network inside OVPM. The feature you are talking about is coming up with v0.3.
