### ISSUE TITLE
Ubuntu Group needs to be "nogroup"

### ISSUE THREAD

**Issue by ozburn** [cad/ovpm#48]
Hello...
Please , i'm expect not bothering you , but the GROUP for ubuntu is nogroup , and reading the code of last version, i suspect was set  nobody ;)

Soon, i will do a new ubuntu installation from zero , and i let you know, if everything is ok ;), i will wait this change, but no hurry..!! 

Thanks again for this great iniciative :)  

I have some ideas for future, based on my actual use... , but basic is the flexibility to configure parameters on server.conf and  ccd files..   

I not set the vpn as default gateway, instead i configure on ccd for especific "user"  routes like below...

I used to fix IP for every user on ccd too...

----------/ccd/cert.cname.jhon.doe.ovpn -----
ifconfig-push 10.0.0.34 255.255.224.0
push "route 10.0.1.10 255.255.255.255"
push "route 10.0.1.15 255.255.255.255"
------------------------------------------------

This way, i just catch traffic from user machine to specific hosts like example above( 10.0.1.10 and 10.0.1.15 ) , everything else goes to users default gateway(local internet).

I have another level of protection, on external firewall, where i create a ip based rule, this is why i use fixed IP on ccd file,  i have low users + -  45, and use this another firewall to control access...

I will try to use an iptables on ovpn server machine too , but  not yet...

Thankyou One more time and sorry my bad english, im from Brasil. o/

Cya.

**Comment by cad** [comment]
@ozburn Right now, I actually make sure the group exists on the host (if not; one is created). So you can use the latest version right away (`v0.1.18`) it won't be a problem. But I will still change the group to nogroup in the next release. So thanks for reporting.

For the configuration you specified this can be easily accomplished with ovpm.

After initializing the vpn server or updating it with `--net 10.0.0.0/19`, you can create a user or update it.

`$ ovpm user create -u vpnuser1 -p 1234 --no-gw --static 10.0.0.34`

Then you can define two ROUTE type networks.

`$ ovpm net def  -n route1 -t ROUTE -c 10.0.1.10/32`
`$ ovpm net def  -n route2 -t ROUTE -c 10.0.1.15/32`

Now you can associate any users to these networks, then the routes will be pushed to the users.

```
$ ovpm net assoc -u vpnuser1 -n route1 
INFO[0000] network associated: user:vpnuser1 <-> network:route1 

$ ovpm net assoc -u vpnuser1 -n route2          
INFO[0000] network associated: user:vpnuser1 <-> network:route2
```
You can see the network table.

```ovpm net list
+---+--------+-----------------------------+-------+----------+--------------------------------+
| # |  NAME  |            CIDR             | TYPE  |  ASSOC   |           CREATED AT           |
+---+--------+-----------------------------+-------+----------+--------------------------------+
| 1 | route1 | 10.0.1.10/32 via vpn-server | ROUTE | vpnuser1 | Thu Sep 21 09:46:15 +0300 2017 |
| 2 | route2 | 10.0.1.15/32 via vpn-server | ROUTE | vpnuser1 | Thu Sep 21 09:46:23 +0300 2017 |
+---+--------+-----------------------------+-------+----------+--------------------------------+
```

**Comment by ozburn** [comment]
Uaw.!!!  Oustanding..!! Thank you for the details explained..! Awesome...  this tutorial helps me a lot..!!
