### ISSUE TITLE
WEB UI Default username and password for First Access

### ISSUE THREAD

**Issue by ozburn** [cad/ovpm#53]
Hello Cad,
              I just did a clean install on Ubuntu 16.04 LTS from scratch and have no issues at all..!!

          Everything works smooth ..!! 

           After the service start, go to http://myovpm.local.ip:8080 , the site is ok and ask for User/Pass.
           I can´t find this information to Log IN, what is needed to access through webUI ?

           Man... your project will help a lot of people and it´s better every release.., thank you for your time and knowledge to keep going...

**Comment by cad** [comment]
@ozburn There are two ways that you can a user with admin privileges.

1. Via cli;
```$ ovpm user create -u <username> -p <password> --admin```
Then login with these credentials.

2. Via Web;
If you can access the web server from it's loopback interface, the authentication is bypassed.

For example you can forward vpn server's localhost via ssh by doing that you will be able to bypass authentication and then create an admin type user. Admin type user can always create/modify/delete other users. 
Example below:

```bash
$ ssh vpn.example.com -L 8081:127.0.0.1:8080
```

Then you can directly access admin dashboard by visiting `http://127.0.0.1:8081` on your computer.

I will cover the topics related to WebUI in the wiki  in close future, upon finishing some improvements on it. Right now it's undocumented.

And thanks for the encouragement. :)
