### ISSUE TITLE
install fresh TUNTAP error

### ISSUE THREAD

**Issue by croziors** [cad/ovpm#61]
Hello
could you help me ?
* ovpmd.service - OpenVPn Manager
   Loaded: loaded (/usr/lib/systemd/system/ovpmd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2017-11-18 18:44:15 UTC; 8min ago
  Process: 318 ExecStart=/usr/sbin/ovpmd (code=exited, status=1/FAILURE)
 Main PID: 318 (code=exited, status=1/FAILURE)

**Comment by cad** [comment]
@croziors Could you do `$ journalctl -u ovpmd` and post the output here?

**Comment by croziors** [comment]
root@vpn1:/home/maxime# journalctl -u ovpmd
-- Logs begin at Sat 2017-11-18 19:24:42 UTC, end at Sun 2017-11-19 13:07:49 UTC
Nov 18 19:24:42 vpn1 systemd[1]: ovpmd.service: Failed to reset devices.list: Op
Nov 18 19:24:42 vpn1 systemd[1]: Started OpenVPn Manager.
Nov 18 19:24:42 vpn1 ovpmd[449]: time="2017-11-18T19:24:42Z" level=info msg="OVP
Nov 18 19:24:42 vpn1 ovpmd[449]: time="2017-11-18T19:24:42Z" level=info msg="con
Nov 18 19:24:42 vpn1 ovpmd[449]: time="2017-11-18T19:24:42Z" level=error msg="ex
Nov 18 19:24:42 vpn1 ovpmd[449]: time="2017-11-18T19:24:42Z" level=info msg="pro
Nov 18 19:24:42 vpn1 ovpmd[449]: time="2017-11-18T19:24:42Z" level=error msg="pr
Nov 18 19:24:42 vpn1 systemd[1]: ovpmd.service: Main process exited, code=exited
Nov 18 19:24:42 vpn1 systemd[1]: ovpmd.service: Unit entered failed state.
Nov 18 19:24:42 vpn1 systemd[1]: ovpmd.service: Failed with result 'exit-code'.
lines 1-11/11 (END)...skipping...
-- Logs begin at Sat 2017-11-18 19:24:42 UTC, end at Sun 2017-11-19 13:07:49 UTC. --
Nov 18 19:24:42 vpn1 systemd[1]: ovpmd.service: Failed to reset devices.list: Operation not permitted
Nov 18 19:24:42 vpn1 systemd[1]: Started OpenVPn Manager.
Nov 18 19:24:42 vpn1 ovpmd[449]: time="2017-11-18T19:24:42Z" level=info msg="OVPM 0.2.6 is running gRPC:9090, REST:8080 ..."
Nov 18 19:24:42 vpn1 ovpmd[449]: time="2017-11-18T19:24:42Z" level=info msg="configurations emitted to the filesystem"
Nov 18 19:24:42 vpn1 ovpmd[449]: time="2017-11-18T19:24:42Z" level=error msg="exit status 1"
Nov 18 19:24:42 vpn1 ovpmd[449]: time="2017-11-18T19:24:42Z" level=info msg="process exited: <nil>"
Nov 18 19:24:42 vpn1 ovpmd[449]: time="2017-11-18T19:24:42Z" level=error msg="process exited unexpectedly: /usr/sbin/openvpn"
Nov 18 19:24:42 vpn1 systemd[1]: ovpmd.service: Main process exited, code=exited, status=1/FAILURE
Nov 18 19:24:42 vpn1 systemd[1]: ovpmd.service: Unit entered failed state.
Nov 18 19:24:42 vpn1 systemd[1]: ovpmd.service: Failed with result 'exit-code'.
~
root@vpn1:/home/maxime# cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.10
DISTRIB_CODENAME=yakkety
DISTRIB_DESCRIPTION="Ubuntu 16.10"
NAME="Ubuntu"
VERSION="16.10 (Yakkety Yak)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.10"
VERSION_ID="16.10"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="http://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=yakkety
UBUNTU_CODENAME=yakkety

**Comment by cad** [comment]
@croziors openvpn seems to stopped unexpectedly. 
Could you do a `$ sudo ovpmd --verbose` to see the detailed log?

**Comment by croziors** [comment]
root@vpn1:/home/maxime# sudo ovpmd --verbose
INFO[0000] OVPM 0.2.6 is running gRPC:9090, REST:8080 ...
DEBU[0000] openvpn executable detected: /usr/sbin/openvpn  ✔
DEBU[0000] openvpn executable detected: /usr/sbin/openvpn  ✔
DEBU[0000] openssl executable detected: /usr/bin/openssl  ✔
DEBU[0000] iptables executable detected: /sbin/iptables  ✔
INFO[0000] configurations emitted to the filesystem
DEBU[0000] transition: 'STOPPED' -> 'STARTING'           cmd=/usr/sbin/openvpn
DEBU[0000] running /usr/sbin/openvpn
DEBU[0000] process is started /usr/sbin/openvpn PID 7199
DEBU[0000] can not enable nat: can not get vpn network interface on the system
DEBU[0000] transition: 'STARTING' -> 'RUNNING'           cmd=/usr/sbin/openvpn
ERRO[0000] exit status 1
INFO[0000] process exited: <nil>
DEBU[0000] transition: 'RUNNING' -> 'EXITED'             cmd=/usr/sbin/openvpn
DEBU[0000] STDOUT(err): Sun Nov 19 16:43:27 2017 OpenVPN 2.3.11 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 22 2017
Sun Nov 19 16:43:27 2017 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Sun Nov 19 16:43:27 2017 Diffie-Hellman initialized with 4096 bit key
Sun Nov 19 16:43:27 2017 Socket Buffers: R=[212992->212992] S=[212992->212992]
Sun Nov 19 16:43:27 2017 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)
Sun Nov 19 16:43:27 2017 Exiting due to fatal error

ERRO[0000] process exited unexpectedly: /usr/sbin/openvpn

**Comment by cad** [comment]
Apparently, this error is not related to ovpm or even openvpn. It's just tun/tap devices are missing on your system.

> Sun Nov 19 16:43:27 2017 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)

Either tun/tap kernel module is not loaded. Or your vps provider (if you have one) has disabled it.

**Comment by croziors** [comment]
thx for resolv i use http://www.tech-and-dev.com/2017/08/enable-tuntap-in-proxmox-4-lxc.html

**Comment by croziors** [comment]
work on promox 5.0

**Comment by cad** [comment]
Great. Closing this then.
