### ISSUE TITLE
tap 100mbits

### ISSUE THREAD

**Issue by croziors** [cad/ovpm#63]
Hello why tap adaptater is only 100Mbits ?
![image](https://user-images.githubusercontent.com/19520104/34084911-9a4601f0-e388-11e7-8e66-913863d9f1c5.png)

**Comment by cad** [comment]
@croziors this device is created by OpenVPN itself. OVPM doesn't create tun/tap devices it just supervises OpenVPN under the hood.

Related issue: OpenVPN/tap-windows/issues/3
