### ISSUE TITLE
 the connection is unavailable

### ISSUE THREAD

**Issue by MrMoronIV** [cad/ovpm#69]
I try to init with my port and hostname, but I get:

ERRO[0001] server can not be initialized: rpc error: code = Unavailable desc = grpc: the connection is unavailable

I also tried: localhost, 127.0.0.1, the public IP, the local IP, everything gives the same result. OVPM is on the same machine as openVPN.

OpenVPN is running fine, currently connected to it and browsing the internet.

**Comment by cad** [comment]
@MrMoronIV which linux distro did you install ovpm?

And what is the output of `$ sudo systemctl status ovpmd` command?

**Comment by MrMoronIV** [comment]
Well the service wasn't running. I followed instructions on the opening page:
yum install ovpm
and then follow the quickstart, starting the service isn't mentioned...

After the service was started the init worked

**Comment by cad** [comment]
@MrMoronIV instructions for enabling and starting the ovpmd service was present in the debian section, but apparently I forgot to put them in the CentOS/Fedora section. Now I have updated the quickstart and this is fixed now.

Thanks for pointing it out!
