### ISSUE TITLE
Support for arm64

### ISSUE THREAD

**Issue by jamezrin** [cad/ovpm#73]
With the rise of arm64 servers it would be great for arm64 to be supported.

The debian repository doesn't provide the arm64 architecture and I tried to compile it on my end but it failed horribly, will attach the output if neccessary, I don't have them now.

Is it feasible? Thanks.

**Comment by cad** [comment]
Would be nice to have but unfortunately TravisCI doesn't support arm64 yet. And I have neither the resources nor the the time to do manual testing for arm64.  So if you would like to give it a try you can check out https://github.com/cad/ovpm/wiki/Development#building to see the build instructions.
