### ISSUE TITLE
[Heads up] comp-lzo is deprecated and potentially vulnerable and no longer recommended

### ISSUE THREAD

**Issue by robshep** [cad/ovpm#75]
Regarding these lines in the config templates:

https://github.com/cad/ovpm/blob/4beee04e17b05064487bf4113ee49938d6149a2b/template/client.ovpn.tmpl#L15

https://github.com/cad/ovpm/blob/4beee04e17b05064487bf4113ee49938d6149a2b/template/server.conf.tmpl#L242

`comp-lzo` is a deprecated option from OpenVPN v2.4 onwards and alternate compression parameters are suggested, but actually no longer recommended.

I have a mixed bag of client versions E.g.  Xenial at 16.04.5 using OpenVPN v2.3.X but Bionic using OpenVPN v2.4.X

[The Notice](https://community.openvpn.net/openvpn/wiki/DeprecatedOptions#a--comp-lzo) doesn't yet specify when this option will be removed, so I guess there is plenty of time.

But with `comp-lzo` on the server, I can't find a way to disable this just by removing `comp-lzo` in the client; there are protocol mismatch errors attempting this. 

Moreover there remain some documented vulnerabilities associated with pre-encryption compression E.g. VORACLE and some OpenVPN service providers have disabled compression as a result, with one commenting that performance was noticeably degraded, but I can't find that reference now. 

I suggest removing the compression option `comp-lzo` on the server and client configs.  

Thanks

https://community.openvpn.net/openvpn/wiki/VORACLE
https://www.bleepingcomputer.com/news/security/voracle-attack-can-recover-http-data-from-vpn-connections/
https://protonvpn.com/blog/voracle-attack/

**Comment by cad** [comment]
I vaguely remember disabling this on the server causing problems on the older clients on some distros, but I'll need to check first to see if I was right.

**Comment by robshep** [comment]
Removing the comp-lzo property breaks clients who have it, but then adding it breaks clients that don't. (It's all or nothing for your network)

I mention this because:

1.  Retaining a deprecated parameter might not stand the test of time.  
1.  It is seemingly becoming the default (and recommended)  to not use compression.

I might suggest an enhancement to allow an option to select the compression scheme in use in the ovpm managed server.
