### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by paulocoghi** [cad/ovpm#89]
Hello Mustafa! First of all, congratulations for the incredible library!

I would like to know if you are still using and maintaining it and, if yes, if you have some text informing the API endpoints.

We have a use case where your library is perfect for.

Thanks!

**Comment by cad** [comment]
@paulocoghi thanks. :slightly_smiling_face: 

Currently, I am working on a complete rewrite of the project with modern idioms and design-changes that'll provide users with enough legroom to utilize it for their own needs and bringing in some of the planned features.

Once it reaches a certain state (v0.3) I'll push those changes. I would suggest waiting until I release v0.3 which I will in a few months.

**Comment by paulocoghi** [comment]
Thanks for the reply!
