### ISSUE TITLE
How to update net mask in server.conf

### ISSUE THREAD

**Issue by vvek82** [cad/ovpm#90]
I want to change the server netmask in the server.conf file but when I restart the ovpmd at that time it automatically takes default configuration.

i.e Default is  server 10.9.0.0 255.255.255.0 and i want server 10.9.0.0 255.255.0.0

**Comment by cad** [comment]
You can update the VPN sever network definition.

Be wary that; 
* If you have any users with statically allocated IP addresses, this operation may cause them to **loose
their static addresses**.

* Please backup your current state file before updating the server network definition.

```bash
$ cp /var/db/ovpm/db.sqlite3 ~/db.sqlite3.bkp
```

Update the network definition with the desired network CIDR.
```bash 
$ ovpm v u -n 10.9.0.0/16  # /16 means 255.255.0.0 for the netmask in CIDR form
```
