### ISSUE TITLE
How to get the ip of a specific user ?

### ISSUE THREAD

**Issue by m2cms** [cad/ovpm#95]
Is there any way to get the IP address of a specific user ?

Same as command "**ovpm net list**", but only for one user and only for IP Address value

**Comment by cad** [comment]
In order to get VPN IP of a specific user you can use the following.

```bash
# replace <username> with the  actual username of which you want to find out its IP address
$ ovpm u l | grep <username> | tr -d ' ' | cut -d'|' -f 4 | cut -d '/' -f 1
```
