### ISSUE TITLE
deleting each user and all connections are lost

### ISSUE THREAD

**Issue by m2cms** [cad/ovpm#97]
Will the openvpn server restart after deleting each user and all connections are lost?

**Comment by m2cms** [comment]
I am looking for a way to delete the key created for the user as well as disconnect the user connection

**Comment by cad** [comment]
@m2cms Unfortunately yes.

For your second question, you can delete the user and the certificate will be revoked. (They can't connect again)

**Comment by m2cms** [comment]
If this happens to one user, what happens to the other users?  Will openvpn restart?

**Comment by cad** [comment]
Unfortunately whenever the state is changed (adding/deleting users etc..) right now OVPM regenerates OpenVPN configurations for the final state, dumps it, and then restarts the OpenVPN process.

But in the future, this wouldn't be the case. See #85.
Github <notifications@github.com> wrote:
“If this happens to one user, what happens to the other users? Will openvpn restart?”
