### ISSUE TITLE
When the VPN server is initialized by the command line, the specified server port and network are not effective.

### ISSUE THREAD

**Issue by 1797890817** [cad/ovpm#98]
When the VPN server is initialized by the command line, the specified server port and network are not effective.
When updating the VPN server configuration, you can change the VPN client network configuration。
`zk@zk-PC:~$ ovpm vpn init --hostname SERVERIP -p 1194 -n 10.18.0.0/16
This operation will cause invalidation of existing user certificates.
After this opeartion, new client config files (.ovpn) should be generated for each existing user.

Are you sure ? (y/N)
y
INFO[0019] vpn initialized                               CIDR=10.9.0.0/24 HOSTNAME=SERVERIP PORT=1197 PROTO=UDP SERVER=OpenVPN
`

**Comment by cad** [comment]
This bug should not be present in latest (v0.2.9) release.
