### ISSUE TITLE
Broken after re-install

### ISSUE THREAD

**Issue by t3r00t** [cad/ovpm#99]
Hello after having issues with OpenVPN , it was disconnecting with KEEP ALIVE TIMEOUT each 60 secs.
After more debbuging and fixing that issue , it was now connected but with no data received...

2 hours of debbuging later i decided do just remove everything and reinstall.

**Commands used :**
_apt-get remove openvpn --purge
apt-get remove ovpm --purge
apt autoremove_

then i installed ovpm back

When i launch the vpn init command it do not work. This is the error i get : 
ERRO[0001] grpc error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:9090: connect: connection refused"

I **cannot start ovpm** that's why i get that **_connection refused_** !
**Command used :** _systemctl start ovpmd_

**Output of systemctl status ovpmd :**
● ovpmd.service - OpenVPn Manager
   Loaded: loaded (/lib/systemd/system/ovpmd.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-08-09 01:09:02 CEST; 5s ago
  Process: 3744 ExecStart=/usr/sbin/ovpmd (code=exited, status=203/EXEC)
 Main PID: 3744 (code=exited, status=203/EXEC)
      CPU: 746us

Aug 09 01:09:02 SERVERNAME systemd[1]: Started OpenVPn Manager.
Aug 09 01:09:02 SERVERNAME systemd[1]: ovpmd.service: Main process exited, code=exited, status=203/EXEC
Aug 09 01:09:02 SERVERNAME systemd[1]: ovpmd.service: Unit entered failed state.
Aug 09 01:09:02 SERVERNAME systemd[1]: ovpmd.service: Failed with result 'exit-code'.

I dont think it's my Firewall i added every rule i could think of and nothing fixed it :/
Here is my Firewall rules ( Useless stuff stripped )
`
iptables -t filter -F

iptables -t filter -X

iptables -t filter -P INPUT DROP
iptables -t filter -P FORWARD DROP
iptables -t filter -P OUTPUT DROP

iptables -A INPUT -m geoip --src-cc CN,HK,RU,JP -j DROP

iptables -A INPUT -m set --match-set ipsum src -j DROP

iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT

iptables -t filter -A INPUT -i lo -j ACCEPT
iptables -t filter -A OUTPUT -o lo -j ACCEPT

iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A OUTPUT -p icmp -j ACCEPT

iptables -A OUTPUT -p udp --dport 53 --sport 32768:61000 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -p udp --sport 53 --dport 32768:61000 -m state --state ESTABLISHED -j ACCEPT

iptables -t filter -A INPUT -p tcp --dport 22 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 22 -j ACCEPT

iptables -t filter -A OUTPUT -p tcp --dport 53 -j ACCEPT
iptables -t filter -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 53 -j ACCEPT
iptables -t filter -A INPUT -p udp --dport 53 -j ACCEPT

iptables -t filter -A OUTPUT -p udp --dport 123 -j ACCEPT

iptables -t filter -A OUTPUT -p tcp --dport 80 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 443 -j ACCEPT

iptables -t filter -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 443 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 8443 -j ACCEPT

# OVPM Changed Here i starting allowing random things trying to solv the OpenVpn and OVPM
iptables -t filter -A INPUT -i eth0 -m state --state NEW -p udp --dport 1194 -j ACCEPT
iptables -t filter -A OUTPUT -p udp --dport 1194 -j ACCEPT

iptables -t filter -A INPUT -p udp --dport 1197 -j ACCEPT

iptables -t filter -A INPUT -i tun+ -j ACCEPT
iptables -A FORWARD -i tun+ -j ACCEPT
iptables -A FORWARD -i tun+ -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i eth0 -o tun+ -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
iptables -t filter -A OUTPUT -o tun+ -j ACCEPT

iptables -t filter -A INPUT -i tun0 -j ACCEPT
iptables -t filter -A OUTPUT -o tun0 -j ACCEPT

iptables -t filter -A INPUT -p tcp --dport 9090 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 8080 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 9090 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 8080 -j ACCEPT
`

**Comment by cad** [comment]
@t3r00t upgrading to v0.2.10 should fix this problem. Please reopen if otherwise.
